arb-translate-api-key: AIzaSyDUfRDLq_NEOz0IhRBTMvLzdq69mQQXLH8
arb-translate-model: gemini-1.5-flash
arb-translate-context: Yapay zeka için yardımcı araçlar ve kredi ile hesap satışı uygulaması
template-arb-file: intl_tr.arb
